// basicReact/src/pages/errorPage/404.tsx
import { themeVariables } from '@/constants/theme'
import { Button } from 'antd'
import { useNavigate } from 'react-router-dom'
import styled from 'styled-components'

/**
 * template
 */
const StyledNotFoundPage = styled.div`
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  width: 100%;
  text-align: center;
  display: flex;
  flex-direction: column;
  align-items: center;
  color: #999;
`
const StyledText = styled.p`
  padding: 0 0 40px 0;
  font-size: 160px;
  color: ${themeVariables.colors.primary};
`
const NotFoundPage = () => {
  // 获取导航函数
  const navigate = useNavigate()
  const handleBack = () => {
    navigate({
      pathname: '/'
    })
  }

  return (
    <StyledNotFoundPage className="container">
      <StyledText>404</StyledText>
      <Button type="primary" onClick={handleBack}>
        回到首页
      </Button>
    </StyledNotFoundPage>
  )
}

export default NotFoundPage

// base-vue/src/views/error-page/404.vue
<template lang="pug">
.error-page
  .content.noFound 404
  .content {{ '您访问的页面不存在' }}
  .foot(@click="back") back
  el-button(type="primary") primary
</template>
<script>
import { defineComponent } from 'vue'
import { useRouter } from 'vue-router'
// import { ElBadge } from 'element-plus'
export default defineComponent({
  name: '404',
  // components: {  },
  setup() {
    const router = useRouter()
    return {
      back: () => {
        router.replace('')
      }
    }
  }
})
</script>
<style lang="stylus" scoped>
.error-page
  text-align center
  display flex
  flex-direction column
  justify-content center
  align-items center
  font-size 28px
  color #999
  height 100%
  width 100%
  .noFound
    font-size 80px
    padding-bottom 40px
  .foot
    margin-top 200px
    .btn
      background #1989fa
      padding 0 80px
</style>
