// basicReact/src/pages/layout/footer/index.tsx
import React from 'react'
import { Button } from 'antd'
import styled from 'styled-components'

const StyledLayoutFooter = styled.div`
  width: 100%;
  height: 60px;
  display: flex;
`

const LayoutFooter: React.FC = () => {
  return (
    <StyledLayoutFooter className="layoutFooter">
      <Button type="primary">我是底部</Button>
    </StyledLayoutFooter>
  )
}

export default LayoutFooter

// basicVue/src/pages/layout/footer/index.vue
<template>
  <div class="layoutFooter">
    <a-button type="primary">我是底部</a-button>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import { Button } from 'ant-design-vue'

export default defineComponent({
  name: 'LayoutFooter',
  components: {
    'a-button': Button
  },
  setup() {
    return {}
  }
})
</script>

<style lang="scss" scoped>
.layoutFooter {
  width: 100%;
  height: 60px;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #fff;
  border-top: 1px solid #f0f0f0;
}
</style>
