// basicReact/src/pages/layout/header/index.tsx
import React, { useState } from 'react'
import { Button } from 'antd'
import styled from 'styled-components'
import { Icon } from '@iconify/react/dist/iconify.js'
import Widgets from '@/pages/layout/components/widgets'

interface HeaderProps {
  className?: string
}

const StyledLayoutHeader = styled.div`
  width: 100%;
  height: 60px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 20px;
  background-color: #fff;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);
`
const HeaderLeft = styled.div`
  display: flex;
  align-items: center;
`
const HeaderRight = styled.div`
  display: flex;
  align-items: center;
`
const StyledSettingBtn = styled(Button)``

const LayoutHeader: React.FC<HeaderProps> = () => {
  const [settingsOpen, setSettingsOpen] = useState(false)
  // 打开设置抽屉
  const handleOpenSettings = () => {
    setSettingsOpen(true)
  }
  // 关闭设置抽屉
  const handleCloseSettings = () => {
    setSettingsOpen(false)
  }

  return (
    <StyledLayoutHeader className="layoutHeader">
      <HeaderLeft>
        <Button type="primary">我是头部</Button>
      </HeaderLeft>
      <HeaderRight>
        <StyledSettingBtn
          type="text"
          shape="circle"
          icon={<Icon icon="tdesign:setting-1" />}
          onClick={handleOpenSettings}
        />
        <Widgets open={settingsOpen} onClose={handleCloseSettings} />
      </HeaderRight>
    </StyledLayoutHeader>
  )
}

export default LayoutHeader

// basicVue/src/pages/layout/header/index.vue
<template>
  <div class="layoutHeader">
    <div class="headerLeft">
      <a-button type="primary">我是头部</a-button>
    </div>
    <div class="headerRight">
      <a-button
        type="text"
        shape="circle"
        :icon="SettingOutlined"
        @click="handleOpenSettings"
      />
      <Widgets :open="settingsOpen" @close="handleCloseSettings" />
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue'
import { Button } from 'ant-design-vue'
import { SettingOutlined } from '@ant-design/icons-vue'
import Widgets from '@/pages/layout/components/widgets/index.vue'

export default defineComponent({
  name: 'LayoutHeader',
  components: {
    'a-button': Button,
    SettingOutlined,
    Widgets
  },
  setup() {
    const settingsOpen = ref(false)
    // 打开设置抽屉
    const handleOpenSettings = () => {
      settingsOpen.value = true
    }
    // 关闭设置抽屉
    const handleCloseSettings = () => {
      settingsOpen.value = false
    }
    return {
      SettingOutlined,
      settingsOpen,
      handleOpenSettings,
      handleCloseSettings
    }
  }
})
</script>

<style lang="scss" scoped>
.layoutHeader {
  width: 100%;
  height: 60px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 20px;
  background-color: #fff;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);
  .headerLeft {
    display: flex;
    align-items: center;
  }
  .headerRight {
    display: flex;
    align-items: center;
  }
}
</style>
