// base-vue-ts/src/views/error-page/404.vue
<template lang="pug">
.error-page
  .content.noFound 404
  ElButton.back(type="primary" @click="back") {{ '返回首页' }}
</template>
<script lang="ts">
import { defineComponent } from 'vue'
import { ElButton } from 'element-plus'
import { useRouter } from 'vue-router'
export default defineComponent({
  name: '404',
  components: { ElButton },
  setup() {
    const router = useRouter()
    return {
      back: () => {
        router.replace('/')
      }
    }
  }
})
</script>
<style lang="stylus" scoped>
.error-page
  width 100%
  height 100%
  padding 30% 0
  text-align center
  display flex
  flex-direction column
  align-items center
  font-size 28px
  color #999
  .noFound
    color $primaryBtnBackground
    font-size 160px
    padding-bottom 40px
  .back
    height auto
    font-size 18px
</style>

// basicReact/src/pages/errorPage/404.tsx
import { themeVariables } from '@/constants/theme'
import { Button } from 'antd'
import { useNavigate } from 'react-router-dom'
import styled from 'styled-components'

/**
 * template
 */
const StyledNotFoundPage = styled.div`
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  width: 100%;
  text-align: center;
  display: flex;
  flex-direction: column;
  align-items: center;
  color: #999;
`
const StyledText = styled.p`
  padding: 0 0 40px 0;
  font-size: 160px;
  color: ${themeVariables.colors.primary};
`
const NotFoundPage = () => {
  // 获取导航函数
  const navigate = useNavigate()
  const handleBack = () => {
    navigate({
      pathname: '/'
    })
  }

  return (
    <StyledNotFoundPage className="container">
      <StyledText>404</StyledText>
      <Button type="primary" onClick={handleBack}>
        回到首页
      </Button>
    </StyledNotFoundPage>
  )
}

export default NotFoundPage
